version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t docker-flask-app .
      - docker tag docker-flask-app:latest $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/docker-flask-app:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/docker-flask-app:latest
      - printf '[{"name":"docker-flask-app","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/docker-flask-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

